const DATA_FILES=["metadata","weapons","mods","compatibility","observations","scoring-profiles","cradle"];
const STORAGE={owned:"marathon-owned-mods-v2",ownedLegacy:"marathon-owned-mods-v1",build:"marathon-saved-build-v1",cradle:"marathon-cradle-v1",scans:"marathon-scan-drafts-v1"};
const statMeta={accuracy:["Accuracy","",false],chargeTime:["Charge time","s",true],voltDrain:["Volt drain","%",true],firepower:["Firepower","",false],handling:["Handling","",false],spreadAngle:["Spread angle","°",true],damage:["Damage","",false],precisionMultiplier:["Precision","×",false],rpm:["RPM","",false],hipfireSpread:["Hipfire spread","°",true],adsSpread:["ADS spread","°",true],crouchSpreadBonus:["Crouch bonus","%",false],movingInaccuracy:["Moving inaccuracy","%",true],equipSpeed:["Equip speed","s",true],adsSpeed:["ADS speed","s",true],weight:["Weight","%",true],recoil:["Recoil","%",true],aimAssist:["Aim assist","°",false],reloadSpeed:["Reload","s",true],range:["Range","m",false],magazineSize:["Magazine","",false],adsZoom:["Zoom","×",false]};
const unitMap={percent:"%",degrees:"°",seconds:"s",multiplier:"×",rounds:"",meters:"m",flat:""};
const state={data:{},route:"home",dbTab:"weapons",dbQuery:"",dbFilter:"",inventory:{},buildSelections:{},conversionRows:[],pendingFile:null,deferredPrompt:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function n(v){return Number(v).toLocaleString(undefined,{maximumFractionDigits:2})}
function baseFmt(stat,v){return `${n(v)}${statMeta[stat]?.[1]||""}`}
function effFmt(e){return `${e.delta>0?"+":""}${n(e.delta)}${unitMap[e.unit]??e.unit??""}`}
function modBySlug(slug){return state.data.mods.find(m=>m.slug===slug)}
function weaponBySlug(slug){return state.data.weapons.find(w=>w.slug===slug)}
function exactForWeapon(slug){return state.data.compatibility.filter(r=>r.weaponSlug===slug&&r.verificationStatus==="live_verified")}
function ownedQty(slug){return Math.max(0,Math.floor(Number(state.inventory[slug])||0))}
function isOwned(slug){return ownedQty(slug)>0}
function inventoryTotals(){const entries=Object.entries(state.inventory).filter(([,qty])=>Number(qty)>0);return{variants:entries.length,copies:entries.reduce((sum,[,qty])=>sum+Math.max(0,Math.floor(Number(qty)||0)),0)}}
function loadLocal(){
  state.inventory={};
  try{
    const current=JSON.parse(localStorage.getItem(STORAGE.owned)||"null");
    if(current&&typeof current==="object"&&!Array.isArray(current))state.inventory=current;
    else if(Array.isArray(current))current.forEach(slug=>state.inventory[slug]=1);
    if(!Object.keys(state.inventory).length){
      const legacy=JSON.parse(localStorage.getItem(STORAGE.ownedLegacy)||"[]");
      if(Array.isArray(legacy))legacy.forEach(slug=>state.inventory[slug]=1);
    }
  }catch{state.inventory={}}
  for(const slug of Object.keys(state.inventory)){
    const qty=ownedQty(slug);
    if(qty>0)state.inventory[slug]=qty;else delete state.inventory[slug];
  }
}
function saveOwned(){localStorage.setItem(STORAGE.owned,JSON.stringify(state.inventory));renderOwned();renderMetrics()}
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),2200)}
async function loadData(){const entries=await Promise.all(DATA_FILES.map(async name=>{const r=await fetch(`data/${name}.json`);if(!r.ok)throw new Error(`Could not load data/${name}.json`);return[name,await r.json()]}));state.data=Object.fromEntries(entries)}
function routeTo(route){state.route=route;$$('[data-view]').forEach(v=>v.classList.toggle('active',v.dataset.view===route));$$('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===route));const labels={home:["Development preview","Home"],database:["Verified records","Database"],build:["Loadout calculator","Build Lab"],cradle:["Progress planning","Cradle"],inventory:["Local collection","Inventory"]};$("#view-eyebrow").textContent=labels[route][0];$("#view-title").textContent=labels[route][1];history.replaceState(null,"",`#${route}`);window.scrollTo({top:0,behavior:"smooth"});if(route==='database')renderDatabase();if(route==='build')renderBuild();if(route==='cradle')renderCradle();if(route==='inventory')renderOwned()}
function bindNav(){$$('[data-route]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();routeTo(el.dataset.route)}))}
function renderMetrics(){const m=state.data.metadata,t=inventoryTotals();$("#side-version").textContent=`v${m.appVersion}`;$("#side-status").textContent=`${m.releaseChannel||"public"} dataset`;$("#home-version").textContent=`v${m.appVersion}`;$("#home-date").textContent=`Updated ${m.generatedOn}`;$("#weapon-count").textContent=state.data.weapons.length;$("#mod-count").textContent=state.data.mods.length;$("#pairing-count").textContent=state.data.compatibility.filter(r=>r.verificationStatus==='live_verified').length;$("#owned-count").textContent=t.copies;renderHomeLocal()}
function renderHomeLocal(){let build=null,cradle=null;try{build=JSON.parse(localStorage.getItem(STORAGE.build)||'null');cradle=JSON.parse(localStorage.getItem(STORAGE.cradle)||'null')}catch{};$("#saved-build-summary").innerHTML=build?`<strong>${esc(weaponBySlug(build.weaponSlug)?.name||build.weaponSlug)}</strong><p>${esc(Object.values(build.selections||{}).filter(Boolean).map(s=>modBySlug(s)?.name).join(', ')||'No mods selected')}</p>`:'No saved build yet.';$("#cradle-summary").innerHTML=cradle?`<strong>Level ${n(cradle.level)}</strong><p>${n(cradle.currentXp)} / ${n(cradle.threshold)} XP · ${n(cradle.energy)} energy available</p>`:'No local Cradle progress saved.'}
function dbFilterOptions(){const select=$("#database-filter");const vals=state.dbTab==='weapons'?[...new Set(state.data.weapons.map(w=>w.category))]:[...new Set(state.data.mods.map(m=>m.slot))];select.innerHTML='<option value="">All</option>'+vals.sort().map(v=>`<option>${esc(v)}</option>`).join('');select.value=state.dbFilter}
function renderDatabase(){
  dbFilterOptions();
  const q=state.dbQuery.toLowerCase();
  let items=[];
  if(state.dbTab==='weapons'){
    items=state.data.weapons
      .filter(w=>(!state.dbFilter||w.category===state.dbFilter)&&[w.name,w.category,w.description,w.ammoType].join(' ').toLowerCase().includes(q))
      .sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name));
    const groups=new Map();
    for(const w of items){if(!groups.has(w.category))groups.set(w.category,[]);groups.get(w.category).push(w)}
    $("#database-results").innerHTML=[...groups.entries()].map(([category,weapons])=>`<section class="database-group"><div class="group-heading"><h2>${esc(category)}</h2><span>${weapons.length} weapon${weapons.length===1?'':'s'}</span></div><div class="database-grid">${weapons.map(w=>{const exact=exactForWeapon(w.slug).length;return `<button class="data-card" data-open-weapon="${esc(w.slug)}"><div class="card-top"><span class="tag">${esc(w.category)}</span><span class="status-chip verified">Live</span></div><h3>${esc(w.name)}</h3><p>${esc(w.description||'Verified base-stat profile.')}</p><div class="tag-row"><span class="tag">${exact} exact mods</span>${w.roundsPerFiringCycle?`<span class="tag">${w.roundsPerFiringCycle} round cycle</span>`:''}</div></button>`}).join('')}</div></section>`).join('');
  }else{
    const families=new Map();
    state.data.mods.forEach(m=>{if(!families.has(m.familySlug))families.set(m.familySlug,[]);families.get(m.familySlug).push(m)});
    items=[...families.values()]
      .filter(g=>(!state.dbFilter||g.some(m=>m.slot===state.dbFilter))&&g.map(m=>[m.name,m.slot,m.description,m.rarity].join(' ')).join(' ').toLowerCase().includes(q))
      .sort((a,b)=>(a[0].slot||'').localeCompare(b[0].slot||'')||a[0].name.localeCompare(b[0].name));
    const groups=new Map();
    for(const family of items){const slot=family[0].slot||'Other';if(!groups.has(slot))groups.set(slot,[]);groups.get(slot).push(family)}
    $("#database-results").innerHTML=[...groups.entries()].map(([slot,families])=>`<section class="database-group"><div class="group-heading"><h2>${esc(slot)}</h2><span>${families.length} famil${families.length===1?'y':'ies'}</span></div><div class="database-grid">${families.map(g=>{const m=g[0],rarities=new Set(g.map(x=>x.rarity.toLowerCase()));return `<button class="data-card" data-open-family="${esc(m.familySlug)}"><div class="card-top"><span class="tag">${esc(m.slot)}</span><span class="tag">${g.length} variant${g.length===1?'':'s'}</span></div><h3>${esc(m.name)}</h3><p>${esc(m.description||'Mod family')}</p><div class="family-rarities"><span class="${rarities.has('enhanced')?'enhanced':''}"></span><span class="${rarities.has('deluxe')?'deluxe':''}"></span><span class="${rarities.has('superior')?'superior':''}"></span></div></button>`}).join('')}</div></section>`).join('');
  }
  $("#database-empty").hidden=items.length>0;
  bindDatabaseCards();
}
function bindDatabaseCards(){$$('[data-open-weapon]').forEach(b=>b.addEventListener('click',()=>openWeapon(b.dataset.openWeapon)));$$('[data-open-family]').forEach(b=>b.addEventListener('click',()=>openFamily(b.dataset.openFamily)))}
function openDrawer(html){$("#drawer-content").innerHTML=html;$("#drawer-backdrop").hidden=false;$("#detail-drawer").classList.add('open');$("#detail-drawer").setAttribute('aria-hidden','false')}
function closeDrawer(){$("#detail-drawer").classList.remove('open');$("#detail-drawer").setAttribute('aria-hidden','true');setTimeout(()=>$("#drawer-backdrop").hidden=true,200)}
function openWeapon(slug){const w=weaponBySlug(slug),records=exactForWeapon(slug);const order=w.displayStats||Object.keys(w.baseStats);openDrawer(`<div class="drawer-title"><p class="eyebrow">${esc(w.category)}</p><h2>${esc(w.name)}</h2><p class="muted">${esc(w.description||'Verified weapon profile.')}</p><div class="tag-row"><span class="status-chip verified">Live verified</span><span class="tag">${records.length} exact pairings</span></div></div><section class="detail-section"><h4>Base stats</h4><div class="detail-grid">${order.filter(k=>statMeta[k]&&typeof w.baseStats[k]==='number').map(k=>`<div class="detail-stat"><span>${esc(statMeta[k][0])}</span><strong>${baseFmt(k,w.baseStats[k])}</strong></div>`).join('')}</div></section><section class="detail-section"><h4>Exact compatible mods</h4><div class="effect-list">${records.length?records.map(r=>{const m=modBySlug(r.modSlug);return `<button class="effect-item text-button" data-open-mod="${esc(m.slug)}"><span>${esc(m.rarity)} ${esc(m.name)}</span><strong>${r.effects.map(e=>effFmt(e)).join(' · ')}</strong></button>`}).join(''):'<p class="muted">No exact effects verified yet.</p>'}</div></section>`);$$('[data-open-mod]').forEach(b=>b.addEventListener('click',()=>openMod(b.dataset.openMod,slug)))}
function ownedButton(slug){const qty=ownedQty(slug);return `<div class="ownership-panel"><div><span class="eyebrow">Local inventory</span><strong>${qty?`${qty} cop${qty===1?'y':'ies'} owned`:'Not currently owned'}</strong></div><div class="quantity-stepper"><button data-owned-dec="${esc(slug)}" aria-label="Decrease quantity">−</button><input data-owned-qty="${esc(slug)}" type="number" min="0" step="1" value="${qty}" aria-label="Owned quantity"><button data-owned-inc="${esc(slug)}" aria-label="Increase quantity">+</button></div></div>`}
function openMod(slug,weaponSlug=null){const m=modBySlug(slug),pairs=state.data.compatibility.filter(r=>r.modSlug===slug);const current=weaponSlug?pairs.find(r=>r.weaponSlug===weaponSlug):null;openDrawer(`<div class="drawer-title"><p class="eyebrow">${esc(m.rarity)} ${esc(m.slot)}</p><h2>${esc(m.name)}</h2><p class="muted">${esc(m.description||'')}</p><div class="tag-row"><span class="tag rarity-${esc(m.rarity.toLowerCase())}">${esc(m.rarity)}</span><span class="tag">${esc(m.weaponClass||m.slot)}</span></div></div>${m.abilityName?`<section class="detail-section"><h4>${esc(m.abilityName)}</h4><p class="muted">${esc(m.abilityDescription||'')}</p></section>`:''}<section class="detail-section"><h4>${current?'Effect on '+esc(weaponBySlug(weaponSlug)?.name):'Captured effects'}</h4><div class="effect-list">${(current?.effects||m.observedEffects||[]).map(e=>`<div class="effect-item"><span>${esc(statMeta[e.stat]?.[0]||e.stat)}</span><strong class="${e.delta>=0?'positive':'negative'}">${effFmt(e)}</strong></div>`).join('')}</div>${current?'':'<p class="fine-print">Captured tooltip values may vary by weapon. Exact pairings are listed below.</p>'}</section><section class="detail-section"><h4>Exact weapon pairings</h4><div class="effect-list">${pairs.length?pairs.map(r=>`<button class="effect-item text-button" data-open-weapon="${esc(r.weaponSlug)}"><span>${esc(weaponBySlug(r.weaponSlug)?.name||r.weaponSlug)}</span><strong>${r.effects.map(e=>effFmt(e)).join(' · ')}</strong></button>`).join(''):'<p class="muted">No exact pairing verified yet.</p>'}</div></section>${ownedButton(slug)}`);bindOwnershipControls(()=>openMod(slug,weaponSlug));$$('[data-open-weapon]').forEach(b=>b.addEventListener('click',()=>openWeapon(b.dataset.openWeapon)))}
function openFamily(family){const variants=state.data.mods.filter(m=>m.familySlug===family).sort((a,b)=>['Enhanced','Deluxe','Superior'].indexOf(a.rarity)-['Enhanced','Deluxe','Superior'].indexOf(b.rarity));const m=variants[0];openDrawer(`<div class="drawer-title"><p class="eyebrow">${esc(m.slot)} family</p><h2>${esc(m.name)}</h2><p class="muted">Rarity variants are grouped as one family. Exact values can still differ by weapon.</p></div>${variants.map(v=>`<section class="detail-section"><div class="panel-heading"><div><p class="eyebrow rarity-${esc(v.rarity.toLowerCase())}">${esc(v.rarity)}</p><h4>${esc(v.name)}</h4></div><button class="text-button" data-open-mod="${esc(v.slug)}">Details</button></div><div class="effect-list">${(v.observedEffects||[]).map(e=>`<div class="effect-item"><span>${esc(statMeta[e.stat]?.[0]||e.stat)}</span><strong>${effFmt(e)}</strong></div>`).join('')}</div></section>`).join('')}`);$$('[data-open-mod]').forEach(b=>b.addEventListener('click',()=>openMod(b.dataset.openMod)))}
function setOwnedQty(slug,qty){qty=Math.max(0,Math.floor(Number(qty)||0));if(qty)state.inventory[slug]=qty;else delete state.inventory[slug];saveOwned()}
function changeOwnedQty(slug,delta){setOwnedQty(slug,ownedQty(slug)+delta);toast(`${modBySlug(slug)?.name||'Item'} quantity: ${ownedQty(slug)}`)}
function bindOwnershipControls(afterChange){
  $$('[data-owned-inc]').forEach(b=>b.addEventListener('click',()=>{changeOwnedQty(b.dataset.ownedInc,1);afterChange?.()}));
  $$('[data-owned-dec]').forEach(b=>b.addEventListener('click',()=>{changeOwnedQty(b.dataset.ownedDec,-1);afterChange?.()}));
  $$('[data-owned-qty]').forEach(input=>input.addEventListener('change',()=>{setOwnedQty(input.dataset.ownedQty,input.value);afterChange?.()}));
}
function populateBuildWeapons(){const withPairs=state.data.weapons.filter(w=>exactForWeapon(w.slug).length).sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name));const groups=new Map();withPairs.forEach(w=>{if(!groups.has(w.category))groups.set(w.category,[]);groups.get(w.category).push(w)});$("#build-weapon").innerHTML=[...groups.entries()].map(([category,weapons])=>`<optgroup label="${esc(category)}">${weapons.map(w=>`<option value="${esc(w.slug)}">${esc(w.name)} · ${exactForWeapon(w.slug).length} verified mods</option>`).join('')}</optgroup>`).join('');let saved=null;try{saved=JSON.parse(localStorage.getItem(STORAGE.build)||'null')}catch{};if(saved&&withPairs.some(w=>w.slug===saved.weaponSlug)){$("#build-weapon").value=saved.weaponSlug;state.buildSelections=saved.selections||{}}}
function renderBuild(){const weaponSlug=$("#build-weapon").value||state.data.weapons.find(w=>exactForWeapon(w.slug).length)?.slug;if(!weaponSlug)return;const w=weaponBySlug(weaponSlug),ownedOnly=$("#owned-only").checked;const groups=new Map();exactForWeapon(weaponSlug).forEach(r=>{const m=modBySlug(r.modSlug);if(ownedOnly&&!isOwned(m.slug))return;if(!groups.has(m.slot))groups.set(m.slot,[]);groups.get(m.slot).push({m,r})});const slotOrder=['Barrel','Underbarrel','Grip','Magazine','Optic','Shield','Generator'];const slots=[...groups.keys()].sort((a,b)=>slotOrder.indexOf(a)-slotOrder.indexOf(b));$("#build-slots").innerHTML=slots.length?slots.map(slot=>`<label class="field"><span>${esc(slot)}</span><select data-build-slot="${esc(slot)}"><option value="">No ${esc(slot.toLowerCase())}</option>${groups.get(slot).map(({m})=>`<option value="${esc(m.slug)}" ${state.buildSelections[slot]===m.slug?'selected':''}>${esc(m.rarity)} ${esc(m.name)}${isOwned(m.slug)?` · OWNED ×${ownedQty(m.slug)}`:''}</option>`).join('')}</select></label>`).join(''):`<div class="empty-card">${ownedOnly?'No owned exact mods for this weapon.':'No exact mod records for this weapon.'}</div>`;$$('[data-build-slot]').forEach(s=>s.addEventListener('change',()=>{state.buildSelections[s.dataset.buildSlot]=s.value;renderBuildOutput(w.slug)}));renderBuildOutput(w.slug)}
function renderBuildOutput(weaponSlug){
  const w=weaponBySlug(weaponSlug),effects=[],chosen=[];
  Object.entries(state.buildSelections).forEach(([slot,slug])=>{if(!slug)return;const r=state.data.compatibility.find(x=>x.weaponSlug===weaponSlug&&x.modSlug===slug&&x.verificationStatus==='live_verified');if(r){effects.push(...r.effects);chosen.push(modBySlug(slug))}});
  const totals={...w.baseStats};
  for(const e of effects){if(typeof totals[e.stat]==='number')totals[e.stat]+=e.delta}
  ['movingInaccuracy','adsSpread','hipfireSpread','recoil','equipSpeed','adsSpeed','reloadSpeed','weight'].forEach(k=>{if(typeof totals[k]==='number')totals[k]=Math.max(0,totals[k])});
  $("#build-title").textContent=w.name;
  $("#build-summary").innerHTML=`<div class="summary-chip"><span>Selected mods</span><strong>${chosen.length}</strong></div>${chosen.map(m=>`<div class="summary-chip"><span>${esc(m.slot)}</span><strong>${esc(m.rarity)} ${esc(m.name)}</strong></div>`).join('')}`;
  const keys=(w.displayStats||Object.keys(w.baseStats)).filter(k=>statMeta[k]&&typeof w.baseStats[k]==='number');
  const changed=keys.map(k=>{const base=w.baseStats[k],delta=(totals[k]??base)-base,lower=statMeta[k][2];const improvement=base===0?null:(lower?-delta:delta)/Math.abs(base)*100;return{k,base,delta,final:totals[k],improvement}}).filter(x=>x.delta!==0);
  $("#build-impact-heatmap").innerHTML=changed.length?`<div class="impact-heading"><div><span class="eyebrow">Relative stat impact</span><strong>Normalized against each base stat</strong></div><div class="impact-legend"><span class="good"></span>Improvement <span class="bad"></span>Tradeoff</div></div><div class="impact-grid">${changed.map(x=>{const good=x.improvement===null?x.delta>0:x.improvement>0;const intensity=Math.min(100,Math.max(10,Math.abs(x.improvement??0)));const label=x.improvement===null?'Flat change':`${x.improvement>0?'+':''}${x.improvement.toFixed(1)}%`;return `<div class="impact-cell ${good?'good':'bad'}" style="--impact:${intensity}%"><span>${esc(statMeta[x.k][0])}</span><strong>${label}</strong><small>${x.delta>0?'+':''}${baseFmt(x.k,x.delta)}</small></div>`}).join('')}</div>`:`<div class="empty-card compact-empty">Select a verified mod to see its stat-impact heatmap.</div>`;
  $("#build-stat-table").innerHTML=`<div class="stat-row header"><span>Stat</span><span>Base</span><span>Change</span><span>Final</span></div>`+keys.map(k=>{const delta=(totals[k]??w.baseStats[k])-w.baseStats[k];const better=statMeta[k][2]?delta<0:delta>0;return `<div class="stat-row"><strong>${esc(statMeta[k][0])}</strong><span>${baseFmt(k,w.baseStats[k])}</span><span class="${delta===0?'muted':better?'positive':'negative'}">${delta>0?'+':''}${baseFmt(k,delta)}</span><strong>${baseFmt(k,totals[k])}</strong></div>`}).join('');
}
function saveBuild(){const data={weaponSlug:$("#build-weapon").value,selections:state.buildSelections,savedOn:new Date().toISOString()};localStorage.setItem(STORAGE.build,JSON.stringify(data));renderHomeLocal();toast('Build saved on this device')}
function loadCradle(){let c;try{c=JSON.parse(localStorage.getItem(STORAGE.cradle)||'null')}catch{};c=c||{level:state.data.cradle.default.level,currentXp:state.data.cradle.default.currentXp,threshold:state.data.cradle.default.levelThreshold,energy:state.data.cradle.default.availableEnergy};$("#cradle-level").value=c.level;$("#cradle-current").value=c.currentXp;$("#cradle-threshold").value=c.threshold;$("#cradle-energy").value=c.energy;state.conversionRows=[{label:'Selected stack',unitValue:10,quantity:0}];renderConversionRows();renderCradle()}
function renderCradle(){const level=+$('#cradle-level')?.value||0,current=+$('#cradle-current')?.value||0,threshold=Math.max(1,+$('#cradle-threshold')?.value||1);const pct=Math.max(0,Math.min(100,current/threshold*100));$("#cradle-progress-bar").style.width=`${pct}%`;$("#cradle-progress-text").textContent=`Level ${n(level)} · ${n(current)} / ${n(threshold)} XP`;$("#cradle-percent").textContent=`${pct.toFixed(1)}%`;const matter=state.conversionRows.reduce((s,r)=>s+(+r.unitValue||0)*(+r.quantity||0),0);const total=current+matter;const crossed=Math.floor(total/threshold);const remainder=total%threshold;$("#matter-total").textContent=n(matter);$("#projected-xp").textContent=n(total);$("#levels-crossed").textContent=n(crossed);$("#xp-remaining").textContent=n(remainder===0?0:threshold-remainder)}
function renderConversionRows(){$("#conversion-rows").innerHTML=state.conversionRows.map((r,i)=>`<div class="conversion-row"><label class="field"><span>Label</span><input data-conv-label="${i}" value="${esc(r.label)}"></label><label class="field"><span>Value each</span><input data-conv-value="${i}" type="number" min="0" value="${r.unitValue}"></label><label class="field"><span>Quantity</span><input data-conv-qty="${i}" type="number" min="0" value="${r.quantity}"></label><button data-remove-conv="${i}" aria-label="Remove row">×</button></div>`).join('');$$('[data-conv-label]').forEach(el=>el.addEventListener('input',()=>state.conversionRows[+el.dataset.convLabel].label=el.value));$$('[data-conv-value]').forEach(el=>el.addEventListener('input',()=>{state.conversionRows[+el.dataset.convValue].unitValue=+el.value;renderCradle()}));$$('[data-conv-qty]').forEach(el=>el.addEventListener('input',()=>{state.conversionRows[+el.dataset.convQty].quantity=+el.value;renderCradle()}));$$('[data-remove-conv]').forEach(el=>el.addEventListener('click',()=>{state.conversionRows.splice(+el.dataset.removeConv,1);renderConversionRows();renderCradle()}))}
function saveCradle(){const c={level:+$("#cradle-level").value,currentXp:+$("#cradle-current").value,threshold:+$("#cradle-threshold").value,energy:+$("#cradle-energy").value,savedOn:new Date().toISOString()};localStorage.setItem(STORAGE.cradle,JSON.stringify(c));renderHomeLocal();toast('Cradle progress saved')}
function handleFile(file){if(!file||!file.type.startsWith('image/'))return toast('Choose an image file');state.pendingFile=file;const reader=new FileReader();reader.onload=()=>{$("#image-preview").src=reader.result;$("#image-preview-wrap").hidden=false;$("#image-meta").innerHTML=`<span class="tag">${esc(file.name)}</span><span class="tag">${n(file.size/1024/1024)} MB</span><span class="tag">${esc(file.type)}</span>`;$("#save-scan-draft").disabled=false;$("#clear-scan").disabled=false};reader.readAsDataURL(file)}
function clearScan(){state.pendingFile=null;$("#inventory-file").value='';$("#image-preview").src='';$("#image-preview-wrap").hidden=true;$("#save-scan-draft").disabled=true;$("#clear-scan").disabled=true}
function saveScanDraft(){if(!state.pendingFile)return;let scans=[];try{scans=JSON.parse(localStorage.getItem(STORAGE.scans)||'[]')}catch{};scans.unshift({id:crypto.randomUUID?.()||String(Date.now()),fileName:state.pendingFile.name,size:state.pendingFile.size,type:state.pendingFile.type,savedOn:new Date().toISOString(),status:'awaiting-recognition'});scans=scans.slice(0,20);localStorage.setItem(STORAGE.scans,JSON.stringify(scans));renderScanHistory();toast('Scan draft metadata saved')}
function renderOwned(){
  const entries=Object.keys(state.inventory).map(slug=>({m:modBySlug(slug),qty:ownedQty(slug)})).filter(x=>x.m&&x.qty>0).sort((a,b)=>(a.m.slot||'').localeCompare(b.m.slot||'')||a.m.name.localeCompare(b.m.name)||a.m.rarity.localeCompare(b.m.rarity));
  const totals=inventoryTotals();
  $("#inventory-total").textContent=`${totals.variants} variant${totals.variants===1?'':'s'} · ${totals.copies} cop${totals.copies===1?'y':'ies'}`;
  const groups=new Map();entries.forEach(x=>{const slot=x.m.slot||'Other';if(!groups.has(slot))groups.set(slot,[]);groups.get(slot).push(x)});
  $("#owned-list").innerHTML=entries.length?[...groups.entries()].map(([slot,items])=>`<section class="owned-group"><h4>${esc(slot)}</h4>${items.map(({m,qty})=>`<div class="owned-item"><div><strong>${esc(m.rarity)} ${esc(m.name)}</strong><small>${esc(m.weaponClass||m.slot||'')}</small></div><div class="quantity-stepper compact"><button data-owned-dec="${esc(m.slug)}">−</button><input data-owned-qty="${esc(m.slug)}" type="number" min="0" step="1" value="${qty}" aria-label="${esc(m.name)} quantity"><button data-owned-inc="${esc(m.slug)}">+</button></div></div>`).join('')}</section>`).join(''):'<div class="empty-card">No mods marked as owned yet.</div>';
  bindOwnershipControls();
  renderScanHistory();
}
function renderScanHistory(){let scans=[];try{scans=JSON.parse(localStorage.getItem(STORAGE.scans)||'[]')}catch{};$("#scan-history").innerHTML=scans.length?scans.map(s=>`<div class="history-item"><div><strong>${esc(s.fileName)}</strong><small>${new Date(s.savedOn).toLocaleString()} · ${n(s.size/1024/1024)} MB</small></div><span class="status-chip pending">Awaiting OCR</span></div>`).join(''):'<div class="empty-card">No scan drafts saved.</div>'}
function bind(){bindNav();$("#close-drawer").addEventListener('click',closeDrawer);$("#drawer-backdrop").addEventListener('click',closeDrawer);$$('[data-db-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-db-tab]').forEach(x=>x.classList.toggle('active',x===b));state.dbTab=b.dataset.dbTab;state.dbFilter='';renderDatabase()}));$("#database-search").addEventListener('input',e=>{state.dbQuery=e.target.value;renderDatabase()});$("#database-filter").addEventListener('change',e=>{state.dbFilter=e.target.value;renderDatabase()});$("#build-weapon").addEventListener('change',()=>{state.buildSelections={};renderBuild()});$("#owned-only").addEventListener('change',renderBuild);$("#save-build").addEventListener('click',saveBuild);$("#reset-build").addEventListener('click',()=>{state.buildSelections={};renderBuild()});['cradle-level','cradle-current','cradle-threshold','cradle-energy'].forEach(id=>$("#"+id).addEventListener('input',renderCradle));$("#save-cradle").addEventListener('click',saveCradle);$("#add-conversion").addEventListener('click',()=>{state.conversionRows.push({label:`Stack ${state.conversionRows.length+1}`,unitValue:0,quantity:0});renderConversionRows()});$("#inventory-file").addEventListener('change',e=>handleFile(e.target.files[0]));const dz=$("#drop-zone");['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('dragging')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('dragging')}));dz.addEventListener('drop',e=>handleFile(e.dataTransfer.files[0]));$("#save-scan-draft").addEventListener('click',saveScanDraft);$("#clear-scan").addEventListener('click',clearScan);$("#clear-owned").addEventListener('click',()=>{if(confirm('Remove all locally stored owned mods?')){state.inventory={};saveOwned()}});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e;$("#install-app").hidden=false});$("#install-app").addEventListener('click',async()=>{if(!state.deferredPrompt)return;state.deferredPrompt.prompt();await state.deferredPrompt.userChoice;state.deferredPrompt=null;$("#install-app").hidden=true})}
async function init(){try{await loadData();loadLocal();renderMetrics();populateBuildWeapons();loadCradle();bind();renderDatabase();renderBuild();renderOwned();const initial=location.hash.slice(1);routeTo(['home','database','build','cradle','inventory'].includes(initial)?initial:'home');if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})}catch(err){console.error(err);document.body.innerHTML=`<main style="padding:40px;color:white"><h1>Could not load the dataset</h1><p>${esc(err.message)}</p><p>Preview through a local web server rather than opening index.html directly.</p></main>`}}
init();